cards_game/urls.py
from django.contrib import admin
from django.urls import path, include
from game import urls as game_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('game/', include(game_urls, 'game')),
    path('auth/', include('rest_framework.urls')),
]

game/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter
from game.views import (
    GamerViewSet,
    CardTypeViewSet,
    CustGamerViewSet,
    CardViewSet,
    DeckViewSet,
    HomeView,
    GamersListView,
    GamerDetail,
    DeckDetail,
    CardEdit,
)

app_name = 'game'

router = DefaultRouter()

router.register('api/gamer', GamerViewSet)
router.register('api/card_type', CardTypeViewSet)
router.register('api/tst', CustGamerViewSet)
router.register('api/card', CardViewSet)
router.register('api/deck', DeckViewSet)

urlpatterns = [
    path('', HomeView.as_view()),
    path('gamer', GamersListView.as_view()),
    path('gamer/<int:pk>', GamerDetail.as_view(), name='gamer_detail'),
    path('deck/<int:pk>', DeckDetail.as_view(), name='deck_detail'),
    path('card/<int:pk>/edit', CardEdit.as_view(), name='card_edit'),
]
urlpatterns += router.urls

game/models.py
from django.db import models
from django.contrib.auth.models import User


TRADE_STATUSES = (
    ('posted', 'размещено'),
    ('canceled', 'отменено'),
    ('completed', 'завершено'),
)


class CardType(models.Model):
    type_name = models.CharField(
        'название',
        max_length=30,
        null=False,
        default='',
    )
    is_active = models.BooleanField('активен', default=True)

    class Meta:
        verbose_name = 'тип карты'
        verbose_name_plural = 'типы карт'

    def __str__(self) -> str:
        return self.type_name

    def __repr__(self) -> str:
        return f'<CardType "{self.type_name}">'


class Card(models.Model):
    display_name = models.CharField(
        'название',
        max_length=30,
        null=False,
        default='',
    )
    strength = models.SmallIntegerField('сила')
    card_type = models.ForeignKey(
        CardType,
        on_delete=models.CASCADE,
        verbose_name='тип карты',
        # editable=False,
    )
    deck = models.ForeignKey(
        'Deck',
        on_delete=models.CASCADE,
        verbose_name='колода',
    )

    class Meta:
        verbose_name = 'карта'
        verbose_name_plural = 'карты'

    def __str__(self) -> str:
        return f'{self.card_type.type_name.capitalize()} ' + \
            f'{self.display_name.capitalize()}'

    def __repr__(self) -> str:
        return f'<Card "{self.display_name}">'


class Deck(models.Model):
    display_name = models.CharField(
        'название',
        max_length=30,
        null=False,
        default='',
    )

    class Meta:
        verbose_name = 'колода'
        verbose_name_plural = 'колоды'

    def __str__(self) -> str:
        return self.display_name

    def __repr__(self) -> str:
        return f'<Deck "{self.display_name}">'


class Gamer(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.DO_NOTHING,
        verbose_name='пользователь',
    )
    deck = models.OneToOneField(
        Deck,
        on_delete=models.CASCADE,
        verbose_name='колода',
    )
    balance = models.DecimalField(
        'баланс',
        max_digits=10,
        decimal_places=2,
    )

    class Meta:
        verbose_name = 'игрок'
        verbose_name_plural = 'игроки'

    def __str__(self) -> str:
        return self.user.username

    def __repr__(self) -> str:
        return f'<Gamer "{self.user.username}">'


class TradePosition(models.Model):
    card = models.ForeignKey(
        Card,
        on_delete=models.SET_NULL,
        verbose_name='карта',
        null=True,
    )
    price = models.DecimalField(
        'цена',
        max_digits=10,
        decimal_places=2,
    )
    status = models.CharField(
        'статус',
        max_length=10,
        choices=TRADE_STATUSES,
    )
    seller = models.ForeignKey(
        Gamer,
        on_delete=models.SET_NULL,
        verbose_name='продавец',
        related_name='seller',
        null=True,
    )
    buyer = models.ForeignKey(
        Gamer,
        on_delete=models.SET_NULL,
        verbose_name='покупатель',
        related_name='buyer',
        null=True,
        blank=True,
    )
    create_date = models.DateTimeField(
        'дата создания',
        auto_now=True,
    )
    deal_date = models.DateTimeField(
        'дата сделки',
        blank=True,
    )

    class Meta:
        verbose_name = 'торговая позиция'
        verbose_name_plural = 'торговые позиции'

    def __str__(self) -> str:
        return f'{self.seller.user.username} - {self.card.__str__()}'

    def __repr__(self) -> str:
        return f'<TradePosition seller:"{self.seller.user.username}" ' + \
            f'card:"{self.card.__str__()}"'

game/forms.py
from django.forms import (
    ModelForm,
)
from game.models import Card


class CardForm(ModelForm):
    class Meta:
        model = Card
        fields = ['display_name']

game/views.py
from typing import List
from django.db.models import query
from django.shortcuts import render, HttpResponse
from django.views.generic import (
    View,
    TemplateView,
    RedirectView,
    DetailView,
    ListView,
    UpdateView,
)
from rest_framework.viewsets import ModelViewSet, ReadOnlyModelViewSet
from game.serializers import (
    GamerSerializer,
    CardTypeSerializer,
    CustGamerSerializer,
    CardSerializer,
    DeckSerializer,
)
from game.models import (
    Gamer,
    CardType,
    Card,
    Deck,
)
from game.forms import (
    CardForm,
)


###############################################################################
##                              VIEWSETS FOR API                             ##
###############################################################################


class GamerViewSet(ReadOnlyModelViewSet):
    serializer_class = GamerSerializer
    queryset = Gamer.objects.all()


class CustGamerViewSet(ModelViewSet):
    serializer_class = CustGamerSerializer
    queryset = Gamer.objects.all()


class CardTypeViewSet(ReadOnlyModelViewSet):
    serializer_class = CardTypeSerializer
    queryset = CardType.objects.filter(is_active=True)


class CardViewSet(ModelViewSet):
    serializer_class = CardSerializer
    queryset = Card.objects.all()


class DeckViewSet(ModelViewSet):
    serializer_class = DeckSerializer
    queryset = Deck.objects.all()



###############################################################################
##                              VIEWS FOR PAGES                              ##
###############################################################################


class HomeView(TemplateView):
    template_name = "home.html"


class GamersListView(ListView):
    model = Gamer
    context_object_name = 'gamers'
    template_name = 'gamers_list.html'
    
    def get_queryset(self):
        return self.model.objects.all()


class GamerDetail(DetailView):
    model = Gamer
    template_name='gamer_detail.html'
    context_object_name = 'gamer'


class DeckDetail(DetailView):
    model = Deck
    template_name='deck_detail.html'
    context_object_name = 'deck'


class CardEdit(UpdateView):
    form_class = CardForm
    model = Card
    template_name = 'card_edit.html'
    context_object_name = 'card'

game/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}Главная страница{% endblock title %} | Картчная игра</title>
    <link rel="stylesheet" href="{% static 'css/game.css' %}">
</head>
<body>
    <div class="canva">
    {% block canva %}
    Здесь будет текст
    {% endblock canva %}
    </div>
</body>
</html>

game/templates/card_edit.html
{% extends 'base.html' %} 

{% block canva %}
<form action="." method="post">
    <h1>{{card.display_name}}</h1>
    <p>Класс: {{card.card_type.type_name}}</p>
    <p>Сила: {{card.strength}}</p>
    {{form.as_p}}
    <button type="submit">Сохранить</button>
</form>
{% endblock canva %}

game/templates/deck_detail.html
{% extends 'base.html' %} {% block canva %}
<h1>{{deck.display_name}}</h1>
<p><a href="">Редактировать</a></p>
{% for card in deck.card_set.all %}
<div class="card">
    <h3>{{forloop.counter0|add:"1"}}. Карта {{card.display_name|capfirst}}</h3>
    <p><a href="{% url 'game:card_edit' card.pk %}">Редактировать</a></p>
    <p>Класс: {{card.card_type.type_name|capfirst}}</p>
    <p>Сила: {{card.strength}}</p>
</div>
{% endfor %} {% endblock canva %}

game/templates/gamer_detail.html
{% extends 'base.html' %}
{% block canva %}
<h1>Игрок {{gamer.user.username}}</h1>
<p>Баланс - {{gamer.balance}}</p>
<p><a href="{% url 'game:deck_detail' gamer.deck.pk %}">Колода</a></p>
{% endblock canva %}

game/templates/gamers_list.html
{% extends 'base.html' %}
{% block canva %}
    <h1>Список игроков</h1>
    {% for gm in gamers %}
    <p><a href="{% url 'game:gamer_detail' gm.pk %}">{{gm.user.username}}</a> - {{gm.balance}}</p>
    {% endfor %}
{% endblock canva %}

game/templates/home.html
{% extends 'base.html' %}
{% block canva %}
<h1>Карточная игра</h1>
<p><a href="">раз</a></p>
<p><a href="">два</a></p>
<p><a href="">три</a></p>
{% endblock canva %}